name: Update Data
on:
  schedule:
    - cron: '0 0 * * *' # Joka yö klo 00:00
  workflow_dispatch: # Mahdollistaa käsin käynnistyksen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - name: Install dependencies
        run: pip install requests
      - name: Fetch data
        run: python fetch_data.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Konkurssibotti'
          git config --global user.email 'bot@github.com'
          git add konkurssit.json
          git commit -m "Päivitetty konkurssitiedot" || exit 0
          git push
